### ISSUE TITLE
Workaround for filters with commas?

### ISSUE THREAD

**Issue by dylinmaust** [Biarity/Sieve#21]
Is there any way to workaround the comma limitation?

> Don't forget to remove commas (,), brackets ((, )), and pipes (|) from any {Value} fields

**Comment by Biarity** [comment]
Currently no, you'd have to write your own [ISieveModel](https://github.com/Biarity/Sieve/blob/master/Sieve/Models/SieveModel.cs) that doesn't use comma delimiters. 

I am currently in the process of rewriting the parser in a more proper framework, so in the future you'd be able to use escape sequences, etc.

**Comment by dylinmaust** [comment]
Rather than create my own ISieveModel, I opted to URL encode filter values and decode them in a custom SieveProcessor, specifically in the ApplyFiltering method. I haven't thoroughly tested it, but it seems to work so far. But it's definitely a hack!

```
dynamic constantVal = converter.CanConvertFrom(typeof(string))
						  ? converter.ConvertFrom(filterTerm.Value)
						  : Convert.ChangeType(filterTerm.Value, property.PropertyType);

if (constantVal != null && constantVal.GetType() == typeof(string))
{
	constantVal = Uri.UnescapeDataString(filterTerm.Value);
}
```

I'm looking forward to the updated parser. Thanks for a great library.

**Comment by Biarity** [comment]
You can now use backslashes to escape commas and pipes.

**Comment by mrjrdg** [comment]
Hi @Biarity i have a problem with escaping commas. Even when i escape comma there is no way to remove the escape character from the query that asp send to sql server.

Exemple :

1. In my database i have a column named title and the value is "my title, test".
2.  the filter of sieve model will be Filters=Title==my title\, test
3. in the sieveprocessor the value change for Filters=Title==my title\\, test
4. when the request is send to sql server, the where clause is title = 'my title\, test'

so as you can see it will not work since the escape character is still in the request.

**Comment by rpabelada** [comment]
Hi @mrjrdg is your issue has been resolved? I'm also experiencing the same issue.
