### ISSUE TITLE
Frontend client future

### ISSUE THREAD

**Issue by elmankross** [Biarity/Sieve#32]
Is there in plans to write frontend typed client for your library?
I already wrote something like [this](https://gist.github.com/elmankross/f3342b24b2ea68cfd8ab884558c19556) but without "OR" logic, because I know you want to change the parser and it seems incorrect now. Maybe it will be
`filter=((my_param_1==1)&&(my_param_2==2))||(my_param_3==3)`, 'cause I can't write right filter for situation where I need object's list with several values for one property:
`filter=id==(1,2,3,4)`, or I didn't find this one. I know, I can write my own parser, but I want it out of the box because it's a base ability :)

**Comment by Biarity** [comment]
Unfortunately I don't have any plans for writing a client-side library right now. If I do change the parser in the future you'd have nothing to worry about since I don't plan on making any breaking changes. The rewrite would be strictly adding features or just changing behind-the-scenes implementation code without modifying the public API.

For filters with >1 value, that is also planned as part of the parser rewrite (something like `(id==(1|2|3|4))`).
