### ISSUE TITLE
Case insensitive starts-with (_=) and contains (@=) operators

### ISSUE THREAD

**Issue by tflanitzer** [Biarity/Sieve#6]
The mentioned operators are case sensitive. I know that it is possible to implement custom operators but I would claim that most scenarios require a case insensitive comparison.

**Comment by Biarity** [comment]
Working on it! I'll make the `==`, `@=`, and `_=` operators case-insensitive and add new `==*`, `@=*`, and `_=*` case-sensitive operators.

**Comment by tflanitzer** [comment]
Thank you, though I am a little unhappy that you changed your mind to make the "special" operators case insensitive, not the default ones. If I remember correctly, in your unedited reply, it was the other way around.

**Comment by Biarity** [comment]
Yep that was the plan originally - but I ran into something I didn't anticipate while working on it. Case-insensitive operators are a "special" case in that they only apply for strings (implementation uses `ToUpper`). And since filter properties can be of other types (for example `int` since Sieve does not convert everything into strings), I chose to make the default operators case-sensitive (the general case that doesn't assume a type). I also didn't want to break compatibility with projects that already somehow rely on the case-sensitive nature of existing operators. By using a case-insensitive operator, you're explicitly telling Sieve that a string is involved.

Really sorry about the confusion! If you think I missed something, I'd be happy to give this more consideration and change things.
